version: '3.4'
volumes:
  volume:

services:
  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: OcelotApiGateway/Dockerfile
    container_name: gateway
    env_file:
        - .env
    ports:
      - 5000:5000
    depends_on:
        - db

  webapplication1:
     build:
      context: .
      dockerfile: WebApplication1/Dockerfile
     container_name: customer  
     env_file:
        - .env
     ports:
        - 5001:5001 
     depends_on:
        - db

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    env_file:
        - .env
    ports:
        - 1433:1433
    container_name: db
   
